export {default as Nav} from './Nav'
export {default as Header} from './Header'
export {default as Event} from './Event'
export {default as Quote} from './Quote'
export {default as  About} from './About'
export {default as  Footer} from './Footer'